# Generated by Django 5.1.6 on 2026-05-31 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_company_description_company_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
