# Generated by Django 5.1.6 on 2026-05-30 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_code'),
        ('suppliers', '0002_company_description_company_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('headers', models.JSONField()),
                ('rows', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_files', to='suppliers.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
